### ISSUE TITLE
ERD Diagram

### ISSUE THREAD

**Issue by jtaneja1** [jtaneja1/wiseowl#10]
The ERD Diagram for the WiseOwl application

**Comment by dbennet4** [comment]
![wiseowl_erd_diagram](https://user-images.githubusercontent.com/29156403/27020136-2e7e8faa-4f04-11e7-8125-c37233cbd564.png)

Do you need the model file as well, or will the picture work by itself?

**Comment by dbennet4** [comment]
![wiseowl_erd_diagram](https://user-images.githubusercontent.com/29156403/27067479-b53632ce-4fd0-11e7-87f0-f5ba8153cc47.png)

I'm just uploading this here so I can put the new ERD Diagram (the one including password encryption) on the wiki.
