### ISSUE TITLE
SQL scripts creation (username & encrypted passwords)

### ISSUE THREAD

**Issue by jtaneja1** [jtaneja1/wiseowl#11]
SQL scripts for creating the database, including username and encrypted passwords

**Comment by dbennet4** [comment]
We'll probably have to encrypt the user passwords again, so I'm thinking about doing so with a salt (like I did last time) as described here: https://www.mssqltips.com/sqlservertip/4037/storing-passwords-in-a-secure-way-in-a-sql-server-database/

What do you guys think of that?
