### ISSUE TITLE
JUnit Test case setup for Login

### ISSUE THREAD

**Issue by jtaneja1** [jtaneja1/wiseowl#16]
JUnit test cases setup for automated testing of the Login Service

**Comment by dbennet4** [comment]
How come you assigned me and then immediately unassigned me? Was that just so it would send me an e-mail, or am I not supposed to work on this yet?

**Comment by jtaneja1** [comment]
I just assigned this task to you, since you have completed the previous task

**Comment by dbennet4** [comment]
I completed the tests for the model classes. Is the code set up so it can access the server yet, or do I have to wait to make tests for the non-model classes? If the former, where would I find the info required to make the test code access the server (such as the HttpSession for the UserController class's loginUser method)?

**Comment by jtaneja1** [comment]
The jUnit test code which tests the Service method (loginUser) does not need to access any server. It will test the service class just like the model java class
