### ISSUE TITLE
Elevator Pitch/Advertisement

### ISSUE THREAD

**Issue by jtaneja1** [jtaneja1/wiseowl#6]

**Comment by jdmiller86** [comment]
Initial Pitch:

"We often don't think of books when it comes to information technology but they remain a vital tool for learning and pleasure. Almost every university requires the use of books for learning purposes, and virtually every topic is enriched by writing on the subject.

The WiseOwl application seeks to enhance the experience and integrate one of the oldest pieces of information technology with some of the newest. Efficient note taking can be performed using the application and allow students and researchers to efficiently document notes and self review works for later review. The information can be accessed from a variety of platforms from the cloud.

How often have you learned something reading and then had to constantly refer back to the material? This application will allow you to quickly refer to your notes and get back to the meat of the book you read. How much time have you spent looking back at material you've already reviewed? How many times have you lamented lost notes from prior readings?"
