### ISSUE TITLE
Testing on at least 3 different screen sizes to confirm proper rendering(Mobile, tablet, PC)

### ISSUE THREAD

**Issue by jtaneja1** [jtaneja1/wiseowl#85]

**Comment by dbennet4** [comment]
PC: 
No problems

Mobile: 
The main menu covers the page headings when extended, even if none of the submenus are extended. As the menu stays extended when going from one page to another, using the menu to go from the "Add Completed Book" page to the "Add ForLater Book" page (or vice versa) looks like it does nothing unless you retract the menu.

Tablet: 
No problems
